import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "../lib/font";
import ScrollToTop from "@components/ScrollToTop";

export const metadata: Metadata = {
  title: "IDEAL constructions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
