import "./globals.css";
import { roboto } from "../lib/font";
import ScrollToTop from "@components/ScrollToTop";
import Footer from "@components/Footer";
export const metadata = {
  title: "IDEAL constructions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        {children}

        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
