import "./globals.css";
import { roboto } from "../lib/font";
import ScrollToTop from "@components/ScrollToTop";
import Footer from "@components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";
import ScrollToBottom from "@components/ScrollToBottom";
export const metadata = {
  title: "IDEAL constructions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased `}>
        {children}
        <ScrollToTop />
        <ScrollToBottom />
        <Footer />
        <SpeedInsights />
      </body>
    </html>
  );
}
